sudo: required
services:
  - docker

before_install:
  - docker build -t bhanukandregula/docker-react-fun -f Dockerfile.dev .
  - docker ps -a

script:
  - docker run bhanukandregula/docker-react-fun npm run test -- --coverage
  

