sudo: required
services:
  - docker

before_install:
  - docker build -t bhanukandregula/docker-react-run -f Dockerfile.dev .

script:
  - docker run bhanukandregula/docker-react-fun npm run test -- --coverage
  

